apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgis
  namespace: mapster
spec:
  serviceName: postgis
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgis
          image: postgis/postgis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - secretRef:
                name: postgis-secret
          volumeMounts:
            - name: postgis-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: postgis-data
          persistentVolumeClaim:
            claimName: postgis-data
