apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-data
  namespace: mapster
spec:
  resources:
    requests:
      # Base uses 5Gi which is typically too small for importing a ~5GB GPKG.
      # Increase this for cloud deployments.
      storage: 50Gi
